//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace for_Ef_MySql
{
    using System;
    using System.Collections.Generic;
    
    public partial class company_info
    {
        public int id { get; set; }
        public System.DateTime establishDate { get; set; }
        public string establishPlace { get; set; }
        public string Effect { get; set; }
        public string companyEmail { get; set; }
        public string companyMobile { get; set; }
        public string companyTel { get; set; }
        public string companyAddress { get; set; }
        public System.DateTime addDate { get; set; }
        public bool isDelete { get; set; }
    }
}
