//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace for_Ef_MySql
{
    using System;
    using System.Collections.Generic;
    
    public partial class consumer
    {
        public int id { get; set; }
        public string userName { get; set; }
        public string passwordHash { get; set; }
        public string realName { get; set; }
        public string avatar { get; set; }
        public bool gender { get; set; }
        public System.DateTime birthday { get; set; }
        public string mobile { get; set; }
        public string mail { get; set; }
        public string wechatOppenId { get; set; }
        public string wechatNum { get; set; }
        public string wechatQRCodeUrl { get; set; }
        public int contryId { get; set; }
        public int provinceId { get; set; }
        public int cityId { get; set; }
        public int areaId { get; set; }
        public string longitude { get; set; }
        public string latitude { get; set; }
        public int isTeacherStatus { get; set; }
        public int beTeacherAccountId { get; set; }
        public int teachingSeniority { get; set; }
        public bool isCanTeaching { get; set; }
        public int teacherLevelId { get; set; }
        public string teacherLevelRemark { get; set; }
        public string diploma { get; set; }
        public int auditStatsu { get; set; }
        public int errorCount { get; set; }
        public bool isLock { get; set; }
        public System.DateTime lockDate { get; set; }
        public int unlockAccountId { get; set; }
        public bool isBlackList { get; set; }
        public System.DateTime toBlackListDate { get; set; }
        public int toBlackListAccountId { get; set; }
        public System.DateTime addDate { get; set; }
        public bool isDelete { get; set; }
    }
}
