//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace for_Ef_MySql
{
    using System;
    using System.Collections.Generic;
    
    public partial class course
    {
        public int id { get; set; }
        public string courseName { get; set; }
        public string introduction { get; set; }
        public int levelClassifyId { get; set; }
        public int teacherId { get; set; }
        public System.DateTime createTime { get; set; }
        public string totalDuration { get; set; }
        public int browseNumber { get; set; }
        public int subscription { get; set; }
        public bool isFree { get; set; }
        public float price { get; set; }
        public int addAccountId { get; set; }
        public bool isDelete { get; set; }
    }
}
