//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace for_Ef_MySql
{
    using System;
    using System.Collections.Generic;
    
    public partial class course_evaluate
    {
        public int id { get; set; }
        public int parentId { get; set; }
        public int consumerId { get; set; }
        public int teacherId { get; set; }
        public int applyId { get; set; }
        public int conurseArraId { get; set; }
        public int evaluateLevel { get; set; }
        public string evaluateContent { get; set; }
        public System.DateTime addDate { get; set; }
        public bool isDelete { get; set; }
    }
}
