//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace for_Ef_MySql
{
    using System;
    using System.Collections.Generic;
    
    public partial class mag_modules
    {
        public int id { get; set; }
        public string name { get; set; }
        public int parentId { get; set; }
        public int menuType { get; set; }
        public string relativeUrl { get; set; }
        public string htmlText { get; set; }
        public string controller { get; set; }
        public string action { get; set; }
        public string parameter { get; set; }
        public int isShowOnMenu { get; set; }
        public int moduleCate { get; set; }
        public bool isDelete { get; set; }
    }
}
