//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace for_Ef_MySql
{
    using System;
    using System.Collections.Generic;
    
    public partial class mag_user
    {
        public int id { get; set; }
        public string userName { get; set; }
        public string passWordHash { get; set; }
        public bool isSupper { get; set; }
        public string mobile { get; set; }
        public string realName { get; set; }
        public int roleId { get; set; }
        public string addRoleMuduleId { get; set; }
        public string removeRoleMuduleId { get; set; }
        public string lastLoginIp { get; set; }
        public System.DateTime addDate { get; set; }
        public bool isDelete { get; set; }
    }
}
