//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace for_Ef_MySql
{
    using System;
    using System.Collections.Generic;
    
    public partial class mag_role_module_permssion
    {
        public int id { get; set; }
        public int roleId { get; set; }
        public int moduleId { get; set; }
        public bool isAllowToAccess { get; set; }
        public System.DateTime created { get; set; }
        public System.DateTime updated { get; set; }
        public int createdBy { get; set; }
        public int updateBy { get; set; }
        public int moduleCate { get; set; }
        public bool isDelete { get; set; }
    }
}
