//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace for_Ef_MySql
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_short_message
    {
        public int id { get; set; }
        public int messType { get; set; }
        public int consumerId { get; set; }
        public string mobileNum { get; set; }
        public int accountId { get; set; }
        public string messageContent { get; set; }
        public System.DateTime sendDate { get; set; }
        public bool isDelete { get; set; }
    }
}
