//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo_01
{
    using System;
    using System.Collections.Generic;
    
    public partial class consumer
    {
        public int id { get; set; }
        public string userName { get; set; }
        public string passwordHash { get; set; }
        public string realName { get; set; }
        public string avatar { get; set; }
        public Nullable<bool> gender { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public string mobile { get; set; }
        public string mail { get; set; }
        public string wechatOppenId { get; set; }
        public string wechatNum { get; set; }
        public string wechatQRCodeUrl { get; set; }
        public Nullable<int> contryId { get; set; }
        public Nullable<int> provinceId { get; set; }
        public Nullable<int> cityId { get; set; }
        public Nullable<int> areaId { get; set; }
        public string longitude { get; set; }
        public string latitude { get; set; }
        public Nullable<int> isTeacherStatus { get; set; }
        public Nullable<int> beTeacherAccountId { get; set; }
        public Nullable<int> teachingSeniority { get; set; }
        public Nullable<bool> isCanTeaching { get; set; }
        public Nullable<int> teacherLevelId { get; set; }
        public string teacherLevelRemark { get; set; }
        public string diploma { get; set; }
        public Nullable<int> auditStatsu { get; set; }
        public Nullable<int> errorCount { get; set; }
        public Nullable<bool> isLock { get; set; }
        public Nullable<System.DateTime> lockDate { get; set; }
        public Nullable<int> unlockAccountId { get; set; }
        public Nullable<bool> isBlackList { get; set; }
        public Nullable<System.DateTime> toBlackListDate { get; set; }
        public Nullable<int> toBlackListAccountId { get; set; }
        public Nullable<System.DateTime> addDate { get; set; }
        public Nullable<bool> isDelete { get; set; }
    }
}
