//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo_01
{
    using System;
    using System.Collections.Generic;
    
    public partial class consumer_apply
    {
        public int id { get; set; }
        public Nullable<int> consumerId { get; set; }
        public Nullable<int> curriculumId { get; set; }
        public Nullable<int> applyStatus { get; set; }
        public Nullable<int> teacherId { get; set; }
        public Nullable<int> allClassHour { get; set; }
        public Nullable<int> nowClassHour { get; set; }
        public Nullable<int> consumerNowContryId { get; set; }
        public Nullable<int> consumerNowProvinceId { get; set; }
        public Nullable<int> consumerNowCityId { get; set; }
        public Nullable<int> consumerNowAreaId { get; set; }
        public string consumerNowLongitude { get; set; }
        public string consumerNowLatitude { get; set; }
        public Nullable<int> recordAccountId { get; set; }
        public Nullable<System.DateTime> recordDate { get; set; }
        public Nullable<System.DateTime> applyDate { get; set; }
        public Nullable<System.DateTime> applySuccessDate { get; set; }
        public Nullable<System.DateTime> applyFinishDate { get; set; }
        public Nullable<System.DateTime> addDate { get; set; }
        public Nullable<bool> isDelete { get; set; }
    }
}
