//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo_01
{
    using System;
    using System.Collections.Generic;
    
    public partial class course
    {
        public int id { get; set; }
        public string courseName { get; set; }
        public string introduction { get; set; }
        public int levelClassifyId { get; set; }
        public int teacherId { get; set; }
        public System.DateTime createTime { get; set; }
        public string totalDuration { get; set; }
        public int browseNumber { get; set; }
        public int subscription { get; set; }
        public bool isFree { get; set; }
        public Nullable<float> price { get; set; }
    }
}
