//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo_01
{
    using System;
    using System.Collections.Generic;
    
    public partial class course_arrangement
    {
        public int id { get; set; }
        public Nullable<int> applyId { get; set; }
        public Nullable<int> consumerId { get; set; }
        public Nullable<int> teacherId { get; set; }
        public Nullable<int> teachingPlaceId { get; set; }
        public Nullable<System.DateTime> classTime { get; set; }
        public Nullable<System.DateTime> addDate { get; set; }
        public Nullable<bool> isDelete { get; set; }
    }
}
