//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo_01
{
    using System;
    using System.Collections.Generic;
    
    public partial class lesson
    {
        public int id { get; set; }
        public string lessonName { get; set; }
        public int courseId { get; set; }
        public string resourcesCoverPath { get; set; }
        public bool resourcesType { get; set; }
    }
}
