//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo_01
{
    using System;
    using System.Collections.Generic;
    
    public partial class mag_modules
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> parentId { get; set; }
        public Nullable<int> menuType { get; set; }
        public string relativeUrl { get; set; }
        public string htmlText { get; set; }
        public string controller { get; set; }
        public string action { get; set; }
        public string parameter { get; set; }
        public Nullable<int> isShowOnMenu { get; set; }
        public Nullable<int> moduleCate { get; set; }
        public Nullable<bool> isDelete { get; set; }
    }
}
