//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo_01
{
    using System;
    using System.Collections.Generic;
    
    public partial class mag_role_module_permssion
    {
        public int id { get; set; }
        public Nullable<int> roleId { get; set; }
        public Nullable<int> moduleId { get; set; }
        public Nullable<bool> isAllowToAccess { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public Nullable<System.DateTime> updated { get; set; }
        public Nullable<int> createdBy { get; set; }
        public Nullable<int> updateBy { get; set; }
        public Nullable<int> moduleCate { get; set; }
        public Nullable<bool> isDelete { get; set; }
    }
}
