//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo_01
{
    using System;
    using System.Collections.Generic;
    
    public partial class teacher_experience
    {
        public int id { get; set; }
        public Nullable<int> teacherId { get; set; }
        public Nullable<System.DateTime> teachingStartDate { get; set; }
        public Nullable<System.DateTime> teachingEndDate { get; set; }
        public string teachingSchool { get; set; }
        public Nullable<int> accountId { get; set; }
        public Nullable<System.DateTime> addDate { get; set; }
        public Nullable<bool> isDelete { get; set; }
    }
}
